### ISSUE TITLE
Cannot make catkin_make install with multi_ontology_reference

### ISSUE THREAD

**Issue by Elsenosy** [EmaroLab/multi_ontology_reference#6]
Hello, 
 
I've installed **multi_ontology_reference**, **ARMOR**, **armor_msgs**
all works when running  `catkin_make` to my workspace, but when i want to run `catkin_make install`, it triggers an error, this error related to the path of **multi_ontology_reference** in the `devel/ `directory

Honestly, i solved it, and i'm just sharing this issue here to help others

I did the following to fix it:
- **Open** multi_ontology_reference/CMakeLists.txt file 
- **Replace** 
```
install(DIRECTORY ${CATKIN_DEVEL_PREFIX}/${CATKIN_GLOBAL_MAVEN_DESTINATION}/it/emarolab/${PROJECT_NAME}/ 
        DESTINATION ${CATKIN_GLOBAL_MAVEN_DESTINATION}/it/emarolab/${PROJECT_NAME})
```

**with** 
```
install(DIRECTORY ${CATKIN_DEVEL_PREFIX}/share/${PROJECT_NAME}/ 
        DESTINATION ${CATKIN_DEVEL_PREFIX}/share/${PROJECT_NAME})
```

Thanks.

**Comment by buoncubi** [comment]
Thank you very much for sharing!
